dashboardPage(header=dashboardHeader(title=span(img(src="FinancYou_image.png", width = 130)),
titleWidth=150,disable=FALSE),
    sidebar = dashboardSidebar(sidebarMenu( tagList(menuItem(text="Connexion",icon=icon("fas fa-unlock-alt"),
tabName="Connexion"),
menuItem(text="Vous",icon=icon("user-circle"),
tabName="Vous"),
menuItem(text="Votre patrimoine",icon=icon("fas fa-piggy-bank"),
tabName="Votre_patrimoine"),
menuItem(text="Vos projets",icon=icon("images"),
tabName="Vos_projets"),
menuItem(text="Vos projections",icon=icon("chart-area"),
tabName="Vos_projections"),
menuItem(text="A venir",icon=icon("exchange-alt"),
tabName="A_venir")),
id="sidebarID"),
disable=FALSE,width=150),
body= dashboardBody(setShadow(class = "box"),
tags$img( src = "vector-triangle-background-215.jpg",
  style = 'top:0;bottom:0; left:0;right:0;margin: auto auto; position: absolute; opacity: 0.5; ', width='100%', height='100%'),

theme_blue_gradient_custom,chooseSliderSkin(skin="Round",color="#ADD8E6"),
tabItems(tabItem(tabName="Connexion",splitLayout(cellWidths=c("20%","50%", "20%"),
"",tagList( tagList(script= tagList(script=br(),
br(),
br(),
br(),
br()),
column(width=12,boxPlusInfo(id =NULL,taglist=tagList(textInput(inputId="pseudo",label=tagList(icon("user"),
 "Username"),
placeholder="Username",width=150),
useShinyalert(),
passwordInput(inputId="passwd",label=tagList(icon("unlock-alt"),
"Password"),
placeholder="Password",width=150),
actionBttn(inputId="Testpseudo",label="Connexion",icon=icon("exchange-alt"),
style="unite",color="primary")),
  width =12,content_num=24),
align="center"),
br())),
"")),
tabItem(tabName="Vous",splitLayout(cellWidths=c("55%","2%", "42%"),
tagList(accordion(accordionItem(tagList(fluidRow(box(title =NULL,tagList(h4(span(uiOutput(outputId="nb_sal"),
 style="color:black; font-weight:bold ;  text-align: center;" ) ) ),
width =12,  status ="maroon",background=NULL,solidHeader=FALSE,collapsible=FALSE,collapsed=FALSE),
uiOutput(outputId="box2"),
boxPlusInfo(id =NULL,taglist=tagList(uiOutput(outputId="slider_epar")),
  width =6,content_num=1),
boxPlusInfo(id =NULL,taglist=tagList(uiOutput(outputId="check_box_evol_sal")),
  width =6,content_num=2))),
id="vous",title=tagList(icon("fas fa-money"),
"Vos ressources"),
color="teal",collapsed=FALSE),
accordionItem(tagList(boxPlusInfo(id ="enf",taglist=noUiSliderInput(inputId="slider_ages",label="faite glisser pour indiquer les ages",min=0,max=25,value=c(0,0,0,0,0,0),
step=1,tooltips=TRUE,margin=0,color="DodgerBlue",format=wNumbFormat( decimals=0)),
  width =6,content_num=10),
boxPlusInfo(id ="pension",taglist=tagList(sliderTextInput(inputId="pensions",label="faite glisser pour indiquer si vous recevez ou versez une pension",choices=c("recue","pas de pension","versée"),
selected="pas de pension",grid=TRUE,dragRange=TRUE),
conditionalPanel(condition="input.pensions!='pas de pension'",textInput(inputId="montant_pension",label="montant de la pension"))),
  width =6,content_num=11)),
id="fiscal",title=tagList(icon("fas fa-users"),
"Votre foyer fiscal"),
color="teal"),
accordionItem(tagList(fluidRow(boxPlusInfo(id ="prioprio",taglist=tagList(uiOutput(outputId="check_box1")),
  width =6,content_num=6),
conditionalPanel(condition="input.check_box1 == '1' ",boxPlusInfo(id ="valeur_bien",taglist=tagList(uiOutput(outputId="slider_immo"),
uiOutput(outputId="check_box2")),
  width =6,content_num=3)),
conditionalPanel(condition="(input.check_box2 == '2')&&(input.check_box1 != '2') ",boxPlusInfo(id ="crd_hab",taglist=tagList(fluidRow(tagList(column(6,tagList(h5("Nombre d'annees totales du crédit",width=6),
uiOutput(outputId="slider_immo_antot"),
h5("Nombre d'années restantes du crédit"),
uiOutput(outputId="slider_immo_anrest"))),
column(6,tagList(h5("Taux d'intérèt du credit en cours"),
uiOutput(outputId="slider_immo_taux"),
h5("Mensualites de remboursement du crédit"),
uiOutput(outputId="slider_immo_mens")))))),
  width =12,content_num=4)),
conditionalPanel(condition="input.check_box1 == '2' ",boxPlusInfo(id ="loyer",taglist=tagList(uiOutput(outputId="slider_loyer")),
  width =6,content_num=7)))),
id="logement",title=tagList(icon("fas fa-home"),
"Votre logement"),
color="teal"),
accordionItem(tagList(uiOutput(outputId="box1"),
conditionalPanel(condition="input.nb_sal==2 ",tagList(boxPlusInfo(id ="2nd_pers",taglist=tagList(uiOutput(outputId="metier2"),
uiOutput(outputId="res_retraite2"),
uiOutput(outputId="slider_evol_sal2")),
  width =6,content_num=9)))),
id="socio_pro",title=tagList(icon("fas fa-briefcase"),
"Votre situation socio-professionnelle"),
color="teal"))),
"", tagList(script=column(width=11,box(title =span("Mettre à jour et sauvegarder", style="color:white; font-weight:bold ;  text-align: center" ),
tagList(actionBttn(inputId="saveBtn1",label="Enregistrement",icon=icon("fas fa-gear"),
style="unite",color="primary")),
width =10,  status =NULL,background="blue",solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE,closable=FALSE,icon=icon("fas fa-graph")),
align="center",offset=1),
boxPlusInfo(id ="graph_repart_revenu",taglist=tagList(withSpinner(plotlyOutput(outputId="Plot_cash",width="auto",height="250px"))),
  width =12,content_num=12),
boxPlusInfo(id ="graph_cumul",taglist=tagList(withSpinner(plotlyOutput(outputId="Plot_cumul",width="auto",height="250px"))),
  width =12,content_num=13)))),
tabItem(tabName="Votre_patrimoine",splitLayout(cellWidths=c("55%","2%", "42%"),
accordion(accordionItem(box(title ="sélection des placements",sliderTextInput(inputId="lis_deroul_plc_type",label="faite glisser pour choisir le type de placement",choices=as.list(unique(as.character(tab2_plc[,23]))),
selected=NULL,grid=TRUE,dragRange=TRUE),
uiOutput(outputId="lis_deroul_plc"),
uiOutput(outputId="UI_plcs"),
column(width=12,box(title ="Valider ce placement",tagList(actionBttn(inputId="Btn_enr_plc",label="Enregistrement",icon=icon("exchange-alt"),
style="unite",color="primary")),
width =6,  status ="primary",background=NULL,solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE,closable=FALSE,icon=FALSE),
align="center",offset=((12-6)/2)),
width =12,  status ="primary",background=NULL,solidHeader=FALSE,collapsible=FALSE),
id="ajout_plc",title=tagList(icon("fas fa-plus-square"),
"Ajouter"),
color="info",collapsed=TRUE),
accordionItem(tagList(DT::dataTableOutput(outputId="tab_plc"),
tags$script(HTML('$(document).on("click", "input", function () {
                       var checkboxes = document.getElementsByName("delete_plc");
                       var checkboxesChecked = [];
                       for (var i=0; i<checkboxes.length; i++) {
                       if (checkboxes[i].checked) {
                      checkboxesChecked.push(checkboxes[i].value);
                      }
                      }
                     Shiny.onInputChange("checked_rows_plc",checkboxesChecked);  })'))),
id="tab_plc",title=tagList(icon("fas fa-pie-chart"),
"Patrimoine"),
color="info",collapsed=FALSE)),
"",boxPlusInfo(id ="graph_repart_eparg",taglist=tagList(withSpinner(plotOutput(outputId="graph_plc",width="auto",height="500px"))),
  width =12,content_num=23))),
tabItem(tabName="Vos_projets",splitLayout(cellWidths=c("55%","2%", "42%"),
accordion(accordionItem(tagList(boxPlusInfo(id ="selection_projets",taglist=tagList(sliderTextInput(inputId="lis_deroul_proj_type",label="faite glisser pour choisir le type de projet",choices=as.list(unique(as.character(tab2[,9]))),
selected=NULL,grid=TRUE,dragRange=TRUE),
uiOutput(outputId="lis_deroul_proj")),
  width =12,content_num=14),
uiOutput(outputId="UI_projets"),
column(width=12,box(title ="Valider ce projet",tagList(actionBttn(inputId="Btn_enr_projet",label="Enregistrement",icon=icon("exchange-alt"),
style="unite",color="primary")),
width =6,  status ="primary",background=NULL,solidHeader=FALSE,collapsible=FALSE,collapsed=FALSE,closable=FALSE,icon=NULL),
align="center",offset=((12-6)/2))),
id="projets",title=tagList(icon("fas fa-umbrella-beach"),
" Décrivez vos projets"),
color="success",collapsed=TRUE),
accordionItem(column(width=12,DT::dataTableOutput(outputId="tab_proj"),
tags$script(HTML('$(document).on("click", "input", function () {
                       var checkboxes_d = document.getElementsByName("delete");
                       var checkboxes_dChecked = [];
                       for (var i=0; i<checkboxes_d.length; i++) {
                       if (checkboxes_d[i].checked) {
                       checkboxes_dChecked.push(checkboxes_d[i].value);
                      }
                      }
                     Shiny.onInputChange("checked_rows_delete_d",checkboxes_dChecked);  })')),
align="center"),
id="tab_proj_",title=tagList(icon("fa fa-sort-amount-desc"),
" L'ensemble de vos projets"),
color="success",collapsed=FALSE)),
"", tagList(script=boxPlusInfo(id ="Chrono_projets",taglist=tagList(plotlyOutput(outputId="graph_proj",width="auto",height="200px")),
  width =12,content_num=15),
boxPlusInfo(id ="Estim_repart_flux",taglist=tagList(plotlyOutput(outputId="graph_proj_CF",width="auto",height="200px")),
  width =12,content_num=16)))),
tabItem(tabName="Vos_projections",splitLayout(cellWidths=c("40%","20%", "40%"),
 tagList(script=valueBox(value="Projections références",subtitle="Vos projections hors projets", icon =icon("exchange-alt"),
color="teal",width=12),
boxPlusInfo(id ="hyp_cumul_epargn",taglist=tagList(plotlyOutput(outputId="graph_flux_optim",width="100%",height="200px")),
  width =12,content_num=17),
boxPlusInfo(id ="Cap_niv_proba",taglist=tagList(plotlyOutput(outputId="graph_quant",width="100%",height="200px")),
  width =12,content_num=18),
boxPlusInfo(id ="Lim",taglist=tagList(plotOutput(outputId="graph_liquide",width="100%",height="200px")),
  width =12,content_num=19)),
 tagList(script=column(width=12,box(title ="Mise à jour",tagList(actionBttn(inputId="btn_optim",label="Calculer",icon=icon("fas fa-gear"),
style="unite",color="primary")),
width =12,  status ="primary",background=NULL,solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE,closable=FALSE,icon=NULL),
align="center"),
column(width=12,valueBoxOutput(outputId="KPI1")),
column(width=12,valueBoxOutput(outputId="KPI2")),
column(width=12,valueBoxOutput(outputId="KPI3")),
column(width=12,valueBoxOutput(outputId="KPI4")),
column(width=12,valueBoxOutput(outputId="KPI5")),
column(width=12,valueBoxOutput(outputId="KPI6"))),
 tagList(script=valueBox(value="Vos projets",subtitle="Projections intégrant vos projets", icon =icon("exchange-alt"),
color="aqua",width=12),
boxPlusInfo(id ="hyp_cumul_epargn2",taglist=tagList(plotlyOutput(outputId="graph_flux_optim_proj",width="100%",height="200px")),
  width =12,content_num=20),
boxPlusInfo(id ="Cap_niv_proba2",taglist=tagList(plotlyOutput(outputId="graph_quant_proj",width="100%",height="200px")),
  width =12,content_num=21),
boxPlusInfo(id ="Lim2",taglist=tagList(plotOutput(outputId="graph_liquide_proj",width="100%",height="200px")),
  width =12,content_num=22)))),
tabItem(tabName="A_venir",carousel(carouselItem(column(width=12,box(title ="Bilan selon plusieurs aspects",div(tags$img(src="futur_dev1.png", width = 500),
style="text-align: center;"),
width =6,  status ="warning",background=NULL,solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE),
align="center",offset=3),
caption="Futures developpements"),
carouselItem(column(width=12,box(title ="Bilan selon plusieurs aspects",div(tags$img(src="futur_dev2.png", width = 500),
style="text-align: center;"),
width =6,  status ="info",background=NULL,solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE),
align="center",offset=3),
caption="Futures developpements"),
carouselItem(column(width=12,box(title ="Bilan selon plusieurs aspects",div(tags$img(src="futur_dev3.png", width = 500),
style="text-align: center;"),
width =6,  status ="primary",background=NULL,solidHeader=TRUE,collapsible=FALSE,collapsed=FALSE),
align="center",offset=3),
caption="Futures developpements"),
id ="carous",indicators=TRUE,width =12)))),
preloader=TRUE,skin=NULL,controlbar=NULL,freshTheme=NULL,scrollToTop=TRUE)
